name: Meu Primeiro Workflow de CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest

    steps:
      - name: Exibe RA - Nome
        run: echo "RA6324623 - Pedro Kommers Medke"   

      - name: Mostra o diretório de trabalho
        run: pwd

      - name: Mostra o nome do repositório
        run: echo "Repositório: ${{ github.repository }}"
